<Project>
	<PropertyGroup>
		<Major>1</Major>
		<Minor>12</Minor>
		<Patch>3</Patch>
		<BuildNumber>84</BuildNumber>
		<ReleaseChannel>beta</ReleaseChannel>
		<ReleaseChannelNumber>11</ReleaseChannelNumber>
	<!--
		<VersionSuffix>alpha</VersionSuffix>
		<VersionSuffix>beta</VersionSuffix>
		<VersionSuffix>rc</VersionSuffix>
		<VersionSuffix>preview</VersionSuffix>
		<VersionSuffix>dev</VersionSuffix>
		<VersionSuffix>exp</VersionSuffix>
	-->

		<VersionPrefix>$(Major).$(Minor).$(Patch).$(BuildNumber)</VersionPrefix>
		<VersionSuffix>$(ReleaseChannel)$(ReleaseChannelNumber)</VersionSuffix>
	</PropertyGroup>
</Project>
